# Generated by Django 3.2.8 on 2021-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Empolyee Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email Address')),
            ],
        ),
    ]
